Traceback (most recent call last):
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/experiments/baseline5.py", line 441, in <module>
    all_results = run_experiments_multiple_datasets(datasets_config, num_runs)
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/experiments/baseline5.py", line 304, in run_experiments_multiple_datasets
    dataset_results = run_dataset_experiments(dataset_config, num_runs)
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/experiments/baseline5.py", line 316, in run_dataset_experiments
    temp_experiment = Baseline5Experiment(dataset_config)
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/experiments/baseline5.py", line 20, in __init__
    self.dataset = self.load_dataset()
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/experiments/baseline5.py", line 31, in load_dataset
    return CLBenchmarkGenerator(
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/data/cl_benchmark_generator.py", line 17, in __init__
    self.image_paths, self.targets, self.domains = self._load_data()
  File "/leonardo_scratch/fast/IscrC_FoundCL/cl/lora-CL/ratatouille/ood/data/cl_benchmark_generator.py", line 34, in _load_data
    for domain in os.listdir(self.dataset_path):
FileNotFoundError: [Errno 2] No such file or directory: '/disk2/dataset/scripts/data/PACS'
